default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: 172.17.0.2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: soswar2_development

test:
  <<: *default
  database: soswar2_test

production:
  adapter: postgresql
  encoding: unicode
  host: ec2-184-73-236-170.compute-1.amazonaws.com
  database: dechri3ns66e7h
  username: gdyhuhumtqqhvr
  password: 2e04cf413b86810f0cc27b6b67db7a5874a889d6397a169fb7ad298474b909e9
  port: 5432
