default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: 172.17.0.2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: soswar2_development

test:
  <<: *default
  database: soswar2_test

production:
  <<: *default
  database: soswar2_production
  username: soswar2
  password: <%= ENV['SOSWAR2_DATABASE_PASSWORD'] %>
